#!/bin/ash
# ISC BIND with DNScrypt Proxy Entry File

echo $(date) - Starting ISC BIND with DNScrypt Proxy

if [ ! -e /data/named.conf ]; then
    cp /etc/templates/named.conf.recursive /data/named.conf
fi

if [ ! -e /data/zones ]; then
    mkdir /data/zones
fi

if [ ! -e /data/rndc ]; then
    mkdir /data/rndc
fi

if [ ! -e /data/rndc/rndc.key ]; then
    rndc-confgen | head -n 5 > /data/rndc/rndc.key
fi

# Detect local address for listen address
echo -e "listen-on {\n$(ip addr | grep inet | grep -v inet6 | awk '{print $2}' | cut -d/ -f1 | sed 's/$/;/' | sed 's/^/\t/')\n};" > /tmp/listenIpAddressDetect

# Detect IPs for Control
echo -e "include \"/data/rndc/rndc.key\";\ncontrols {\n\tinet 127.0.0.1 port 953 allow {\n$(ip addr | grep inet | grep -v inet6 | awk '{print $2}' | cut -d/ -f1 | sed 's/$/;/' | sed 's/^/\t\t/')\n\t} keys { \"rndc-key\"; };\n};" > /tmp/named.conf.control

# Copy example files if no zones are defined
if [ $( ls /data/zones | wc -l) -eq 0 ]; then
    cp /etc/templates/exampleZone.* /data/zones
fi

badZone=0
for name in $(ls /data/zones); do 
    named-checkzone $(cat /data/zones/$name | grep SOA | grep IN | grep "(" | awk '{print $1'}) /data/zones/$name
    if [ $? -ne 0 ]; then 
        echo Zone $name configuration error.
        badZone=1
    else
        if [ $(echo $name | grep "in-addr.arpa" | wc -l) -eq 1 ]; then
            echo "zone \"$name\" {
  type master;
  notify no;
  file \"/data/zones/$name\";
  allow-update { key rndc-key; };
};
" >> /tmp/named.conf.zones
        else
            echo "zone \"$name\" {
  type master;
  file \"/data/zones/name\";
  allow-update { key rndc-key; };
};
" >> /tmp/named.conf.zones
            if [ $(grep internal /data/zones/* | grep "in-addr.arpa" | wc -l) -eq 0 ]; then
                echo "Warning: Zone '$name' does not have a reverse lookup zone defined."
            fi
        fi
    fi
done
if [ $badZone -eq 1 ]; then
    echo There are errors in your zone configuration files.  Startup aborted.
    exit 1
fi

if [ ! -e /data/named.conf.zones ]; then
    cp /tmp/named.conf.zones /data/named.conf.zones
fi

if [ ! -e /data/named.conf.config ]; then
    cp /etc/templates/named.conf.config /data/named.conf.config
fi

/usr/sbin/named-checkconf /data/named.conf
if [ $? -eq 0 ]; then
    echo Configuration check successful.
else
    echo Configuration check failed. Startup aborted.
    exit 1
fi

nohup /usr/sbin/named -c /data/named.conf -f -g

if [ ! -e /data/dnscrypt-proxy.toml ]; then
    cp /etc/templates/dnscrypt-proxy.toml /data/dnscrypt-proxy.toml
fi

/usr/bin/dnscrypt-proxy -config /data/dnscrypt-proxy.toml -check
if [ $? -eq 0 ]; then
    echo Configuration check successful.
else
    echo Configuration check failed. Startup aborted.
    exit 1
fi

/usr/bin/dnscrypt-proxy -config /data/dnscrypt-proxy.toml

exit 0
